layout_spectrum: 0.2583329
typography_spectrum: 0.8060753
color:
  saturation: 0.001803934
  lightness: 0.129351
  brandStrength: 0.3294104
  rhythmicContrast: 0.750902
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Nbh251
